my_list = []
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)
before_insert = my_list.copy()
print("List before insert:", before_insert)
inserted = my_list.insert(1, 15)
print("List after insert:", my_list)
my_list.extend([50, 60, 70])
extented_list = my_list.copy()
print("Extended List:", extented_list)
pop = my_list.pop()
print("Popped Element:", pop)
sort = my_list.sort()
print("Sorted List:", my_list)
indexx = my_list.index(30)
print("Index of 30:", indexx)
